# Generated by Django 5.0 on 2024-01-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
